# Generated by Django 5.2.13 on 2026-04-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Centre', 'Centre'), ('Littoral', 'Littoral'), ('Ouest', 'Ouest'), ('Nord', 'Nord'), ('Sud', 'Sud'), ('Est', 'Est'), ('Adamaoua', 'Adamaoua'), ('Nord-Ouest', 'Nord-Ouest'), ('Sud-Ouest', 'Sud-Ouest'), ('Extrême-Nord', 'Extrême-Nord')], max_length=50)),
                ('ville', models.CharField(max_length=100)),
                ('date_obs', models.DateField()),
                ('observateur', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('pluie', models.FloatField(blank=True, null=True)),
                ('vent', models.FloatField(blank=True, null=True)),
                ('humidite', models.FloatField(blank=True, null=True)),
                ('qualite_air', models.CharField(blank=True, choices=[('Bonne', 'Bonne'), ('Moyenne', 'Moyenne'), ('Mauvaise', 'Mauvaise'), ('Très mauvaise', 'Très mauvaise')], max_length=20, null=True)),
                ('vegetation', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Dégradé', 'Dégradé'), ('Critique', 'Critique')], max_length=20, null=True)),
                ('phenomene', models.CharField(blank=True, choices=[('Sécheresse', 'Sécheresse'), ('Inondation', 'Inondation'), ('Feux de brousse', 'Feux de brousse'), ('Érosion', 'Érosion'), ('Déforestation', 'Déforestation')], max_length=30, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-created_at'],
            },
        ),
    ]
